baseURL = 'https://www.sikaizhao.com/'
languageCode = 'en-us'
title = "Sikai's Blog"
theme = 'stack'

[params.footer]
    motto = "Stay Hungury, Stay Foolish"

[params.comments]
    enabled = false  # 将这里改为 false

